/**
 * Picks and self-hosts the typeface pairing.
 *
 * Two rules drive the choices below. First, the pairing varies with the brand's
 * character, so successive generated sites don't all arrive in the same two
 * faces. Second, the faces are downloaded and served from /fonts — a webfont CDN
 * link is a render-blocking third-party request and, on a locked-down host, a
 * silent fallback to Georgia.
 */
import { mkdir, writeFile } from 'node:fs/promises'
import path from 'node:path'
import type { Typography, Theme } from '../../content/types'

const UA =
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 ' +
  '(KHTML, like Gecko) Chrome/124.0 Safari/537.36'

interface Pairing extends Typography {}

/**
 * Deliberately avoids the faces that have become shorthand for "generated by a
 * model" — Inter and Space Grotesk as the default sans, and the ubiquitous
 * cream-and-Playfair editorial look.
 */
const PAIRINGS: Record<Theme['character'], Pairing> = {
  classic: {
    display: 'Prata',
    body: 'Karla',
    displaySpec: 'Prata:wght@400',
    bodySpec: 'Karla:wght@400..700',
    displayStack: `'Prata', 'Hoefler Text', Georgia, serif`,
    bodyStack: `'Karla', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif`,
    displayTracking: '-0.005em',
  },
  contemporary: {
    display: 'Fraunces',
    body: 'Manrope',
    displaySpec: 'Fraunces:opsz,wght@9..144,400;9..144,600',
    bodySpec: 'Manrope:wght@400..700',
    displayStack: `'Fraunces', 'Iowan Old Style', Georgia, serif`,
    bodyStack: `'Manrope', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif`,
    displayTracking: '-0.018em',
  },
  warm: {
    display: 'Newsreader',
    body: 'Work Sans',
    displaySpec: 'Newsreader:opsz,wght@6..72,400;6..72,500',
    bodySpec: 'Work+Sans:wght@400..700',
    displayStack: `'Newsreader', 'Iowan Old Style', Georgia, serif`,
    bodyStack: `'Work Sans', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif`,
    displayTracking: '-0.012em',
  },
  coastal: {
    display: 'Marcellus',
    body: 'Mulish',
    displaySpec: 'Marcellus:wght@400',
    bodySpec: 'Mulish:wght@400..700',
    displayStack: `'Marcellus', 'Optima', Georgia, serif`,
    bodyStack: `'Mulish', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif`,
    displayTracking: '-0.004em',
  },
  /**
   * Scrisă pentru Casa Irlandeză (șablonul 6). Un display greu și îngust,
   * folosit numai în majuscule și numai la corp mare, peste un serif de text
   * cu duct umanist — combinația de afiș de pub, nu de broșură de hotel.
   *
   * Anton n-are decât greutatea 400, deci specificația TREBUIE să fie
   * `Anton:wght@400`. Dedusă automat (`spec(display, '400;700')`), ar fi
   * ieșit `Anton:wght@400;700`, la care Google Fonts răspunde 400 Bad
   * Request și `installFonts` aruncă. De asta perechea e scrisă aici.
   *
   * Ambele expun latin-ext (U+0100-02BA), deci Ș ș Ț ț cu virgulă dedesubt
   * se randează. Verificat pe răspunsul Google, nu presupus.
   */
  irlandez: {
    display: 'Anton',
    body: 'Abhaya Libre',
    displaySpec: 'Anton:wght@400',
    // 400 și 700, fără 500: skin-ul nu folosește greutatea intermediară
    // nicăieri, iar cele două fișiere ale ei costau 18 KB din bugetul de
    // 120 KB pe care `npm run verifica` îl măsoară.
    bodySpec: 'Abhaya+Libre:wght@400;700',
    displayStack: `'Anton', 'Haettenschweiler', 'Arial Narrow', Impact, sans-serif`,
    bodyStack: `'Abhaya Libre', 'Iowan Old Style', Georgia, serif`,
    // Anton e deja strâns din desen. Mai strâns de-atât, majusculele se
    // ating la 80 px — aici tracking-ul se DESCHIDE, nu se închide.
    displayTracking: '0.005em',
  },
}

export function pickTypography(character: Theme['character']): Typography {
  return PAIRINGS[character]
}

/**
 * Romanian needs the comma-below forms (U+0218–U+021B), which live in Google's
 * `latin-ext` subset. Keeping latin + latin-ext and dropping cyrillic/greek/
 * vietnamese cuts roughly two thirds of the bytes with no visible loss.
 */
function wantedSubset(unicodeRange: string): boolean {
  return unicodeRange.includes('U+0100') || unicodeRange.includes('U+0000')
}

export interface FontResult {
  css: string
  files: number
  bytes: number
  /** Set when latin-ext never appeared — diacritics would fall back. */
  warning?: string
}

export async function installFonts(
  type: Typography,
  publicDir: string
): Promise<FontResult> {
  const url =
    'https://fonts.googleapis.com/css2?family=' +
    encodeURI(type.displaySpec) +
    '&family=' +
    encodeURI(type.bodySpec) +
    '&display=swap'

  const res = await fetch(url, { headers: { 'User-Agent': UA } })
  if (!res.ok) throw new Error(`Google Fonts a răspuns ${res.status} pentru ${url}`)
  const css = await res.text()

  const outDir = path.join(publicDir, 'fonts')
  await mkdir(outDir, { recursive: true })

  const faces: string[] = []
  let files = 0
  let bytes = 0
  let sawExt = false

  // Familiile variabile servesc ACELAȘI fișier pentru fiecare greutate cerută.
  // Fără verificarea asta, un `wght@400;500;600;700` descărca de patru ori
  // exact aceiași octeți, sub patru nume — 227 KB de Mulish în loc de 57 KB.
  // De asta specificațiile de mai sus cer intervale (`400..700`), nu liste;
  // set-ul rămâne ca plasă de siguranță pentru familiile care nu-s variabile.
  const vazute = new Set<string>()

  for (const block of css.match(/@font-face\s*\{[^}]*\}/g) ?? []) {
    const range = block.match(/unicode-range:\s*([^;]+);/)?.[1]?.trim()
    const src = block.match(/url\((https:\/\/[^)]+\.woff2)\)/)?.[1]
    const family = block.match(/font-family:\s*'([^']+)'/)?.[1]
    const weight = block.match(/font-weight:\s*([\d\s]+)/)?.[1]?.trim()
    if (!range || !src || !family || !weight) continue
    if (!wantedSubset(range)) continue
    if (vazute.has(src)) continue
    vazute.add(src)
    if (range.includes('U+0100')) sawExt = true

    const data = Buffer.from(await (await fetch(src, { headers: { 'User-Agent': UA } })).arrayBuffer())
    const slug = `${family.toLowerCase().replace(/\s+/g, '-')}-${weight.replace(/\s+/g, '_')}-${
      range.includes('U+0100') ? 'ext' : 'lat'
    }.woff2`
    await writeFile(path.join(outDir, slug), data)
    files++
    bytes += data.length

    faces.push(
      `@font-face{font-family:'${family}';font-style:normal;font-weight:${weight};` +
        `font-display:swap;src:url('/fonts/${slug}') format('woff2');unicode-range:${range}}`
    )
  }

  return {
    css: faces.join('\n'),
    files,
    bytes,
    warning: sawExt
      ? undefined
      : `Fontul nu expune subsetul latin-ext; diacriticele ș/ț pot cădea pe un fallback.`,
  }
}
