/**
 * Toate componentele de secțiune, într-un singur loc.
 *
 * Șabloanele (C2) importă de aici. O componentă folosită de ≥2 șabloane
 * urcă în motor și apare în lista asta; una folosită de un singur șablon
 * rămâne în șablonul lui (REGULI.md 1).
 */
export { Antet } from './Antet'
export { Subsol } from './Subsol'
export { BaraLipita } from './BaraLipita'
export { Hero } from './Hero'
export { BaraDisponibilitate } from './BaraDisponibilitate'
export { BaraWhatsApp } from './BaraWhatsApp'
export { BlocRezervare } from './BlocRezervare'
export { ModalRezervare } from './ModalRezervare'
export { Calendar } from './Calendar'
export { BandaIncredere } from './BandaIncredere'
export { AntetSectiune } from './AntetSectiune'
export { Facilitati } from './Facilitati'
export { Camere } from './Camere'
export { CardCamera } from './CardCamera'
export { ListaPreturi } from './ListaPreturi'
export { PaginaCamera } from './PaginaCamera'
export { PaginaContact } from './PaginaContact'
export { PaginaOferta } from './PaginaOferta'
export { Poveste } from './Poveste'
export { Semnatura } from './Semnatura'
export { Mozaic } from './Mozaic'
export { Servicii } from './Servicii'
export { AmenitatiChips } from './AmenitatiChips'
export { FeatureAlternant, Features } from './FeatureAlternant'
export { Locatie } from './Locatie'
export { ButonDisponibilitate } from './ButonDisponibilitate'
export { VideoVertical } from './VideoVertical'
export { Prezentare } from './Prezentare'
export { Oferte } from './Oferte'
export { Excursii } from './Excursii'
export { Evenimente } from './Evenimente'
export { Recenzii } from './Recenzii'
export { NotaMedie } from './NotaMedie'
export { Faq } from './Faq'
export { Galerie } from './Galerie'
export { Zona } from './Zona'
export { MeniuRestaurant } from './MeniuRestaurant'
export { HartaFacade } from './HartaFacade'
export { Inchidere } from './Inchidere'
